name: hi_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  google_fonts: ^2.1.0
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0
  firebase_storage: ^10.0.2
  firebase_core: ^1.5.0
  flutter_svg: ^0.22.0
  flutter_screenutil: ^5.0.0+2
  font_awesome_flutter: ^9.1.0
  syncfusion_flutter_sliders: ^19.2.62
  syncfusion_flutter_core: ^19.2.62
  pin_code_fields: ^7.3.0
  syncfusion_flutter_charts: ^19.2.62
  flutter_sound: ^8.3.12
  permission_handler: ^8.1.6
  dotted_border: ^2.0.0+1
  shadow: ^1.0.0
  camera: ^0.9.2+2
  image_gallery_saver: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/vectors/
    - assets/icons/
    - assets/sound_smaple/
    - assets/practice/
    - assets/read/
    - assets/make/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 200
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon/hi_launcher.png"

